config/routes.rb
Rails.application.routes.draw do

  resources :formats
  resources :stores
  resources :record_companies
  resources :countries
  resources :media_gradings
  resources :sleeve_gradings
  root 'pages#home'
  get 'admin', to: 'admin#index'
  get 'blog', to: 'articles#index'

  # Admin routes
  get 'admin/artists', to: 'admin#artists'
  get 'admin/records', to: 'admin#records'
  get 'admin/users', to: 'admin#users'
  get 'admin/settings', to: 'admin#settings'
  get 'admin/grading', to: 'admin#grading'
  get 'admin/countries', to: 'admin#country'
  get 'admin/articles', to: 'admin#articles'
  get 'admin/labels', to: 'admin#labels'
  get 'admin/formats', to: 'admin#formats'
  get 'admin/stores', to: 'admin#stores'

  resources :posts, :artists, :record_companies, :formats, :articles, :sleeve_gradings, :media_gradings, :countries

  namespace :api do
    namespace :v1 do
      resources :artists
      resources :posts
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :post
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :posts
  mount_uploader :artist_image, ArtistUploader
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :posts, :dependent => :delete_all
  mount_uploader :image_flag, FlagUploader,  dependent: :destroy
end

app/models/format.rb
class Format < ApplicationRecord
end

app/models/media_grading.rb
class MediaGrading < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  self.per_page = 12
  scope :by_year, lambda { | year | where(:year => year)}
  scope :is_featured, lambda { | featured | where(:featured => featured)}
  scope :by_artist, lambda { | artist |
    joins(:artist).where(artists: { name: artist })
  }
  scope :by_country, lambda { | country |
    joins(:country).where(countries: { name: country })
  }
  scope :by_label, lambda { | label |
    joins(:record_company).where(record_companies: { name: label })
  }
  mount_uploader :image_front, FrontUploader
  mount_uploader :image_back, BackUploader
  mount_uploader :image_vinyl_a, VinylAUploader
  mount_uploader :image_vinyl_b, VinylBUploader
  belongs_to :format
  belongs_to :artist
  belongs_to :media_grading
  belongs_to :sleeve_grading
  belongs_to :country, :dependent => :delete
  belongs_to :record_company
  belongs_to :store
end

app/models/record_company.rb
class RecordCompany < ApplicationRecord
  mount_uploader :image_label, LabelUploader
end

app/models/sleeve_grading.rb
class SleeveGrading < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end

  def custom_bootstrap_flash
  flash_messages = []
  flash.each do |type, message|
    type = 'success' if type == 'notice'
    type = 'error'   if type == 'alert'
    text = "<script>toastr.#{type}('#{message}');</script>"
    flash_messages << text.html_safe if message
  end
  flash_messages.join("\n").html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def secure_path_for(params, *excluded_params)
    url_for(params.except(*excluded_params).merge(only_path: true).to_enum.to_h)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/admin/articles.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
  .front {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <div align="center">
                  <%= button_to 'New post',{:controller => "articles", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %>
              </div>
              <br>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>Title</th>
                  <th>Subtitle</th>
                  <th>Text</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @articles.each do |a| %>
                  <tr>
                    <td><%= a.title %></td>
                    <td><%= a.subtitle %></td>
                    <td><%= a.text %></td>
                    <td>
                      <%= link_to 'Edit', edit_article_path(a) %> ·
                      <%= link_to 'Delete',  a,  method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/admin/artists.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="row">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>ID</th>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Discogs ID</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @artists.each do |artist| %>
                  <tr>
                    <td><%= artist.id %></td>
                    <td>
                      <% if artist.artist_image.present? %>
                        <%= image_tag artist.artist_image.admin.url, class: "rounded-circle", size: '65x65' %>
                      <% else %>
                        <%= image_tag url_for("user.png"), class: "rounded-circle", size: '65x65' %>
                      <% end %>
                    </td>
                    <td><%= artist.name %></td>
                    <td><%= artist.discogsid %></td>
                    <td>
                      <%= link_to 'Edit', edit_artist_path(artist) %> ·
                      <%= link_to 'Delete',  artist,  method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
    <div class="col-md-3">
          <div class="card card-stats">
            <div class="card-body table-responsive text-center">
              <h5>Advanced</h5>
              <%= button_to 'New artist',{:controller => "artists", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %>
            </div>
          </div>

    </div>
  </div>
</div>

app/views/admin/country.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-6">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <center><h3>Countries</h3></center>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>Name</th>
                  <th>Shortname</th>
                  <th>Flag</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @country.each do |c| %>
                  <tr>
                    <td><%= c.name %></td>
                    <td><%= c.country_code %></td>
                    <td>
                    <% if c.image_flag.present? %>
                      <%= image_tag c.image_flag.admin.url, class: "img-fluid", size: '65x65' %>
                    <% else %>

                    <% end %>
                    </td>
                    <td>
                      <%= link_to 'Edit', edit_country_path(c) %> ·
                      <%= link_to "Delete", country_path(c), method: :delete %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
    </div>
    <div class="col-md-6">
      <div class="card card-stats">
        <div class="card-body table-responsive">
          <center><h3>Actions</h3></center>
          <center><%= button_to 'New',{:controller => "countries", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %></center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/formats.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-6">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <center><h3>Formats</h3></center>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>Name</th>
                  <th>Shortname</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @formats.each do |c| %>
                  <tr>
                    <td><%= c.name %></td>
                    <td><%= c.long_name %></td>
                    <td><%= link_to 'Delete',  c,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
    </div>
    <div class="col-md-6">
      <div class="card card-stats">
        <div class="card-body table-responsive">
          <center><h3>Actions</h3></center>
          <center><%= button_to 'New',{:controller => "formats", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %></center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/grading.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-6">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <center><h3>Media grading</h3></center>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>Name</th>
                  <th>Text</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @media.each do |m| %>
                  <tr>
                    <td><%= m.name %></td>
                    <td><%= m.text %></td>
                    <td><%= link_to 'Delete',  m,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
              <center><%= link_to "New", new_media_grading_path %></center>
          </div>
        </div>
    </div>
    <div class="col-md-6">
      <div class="card card-stats">
        <div class="card-body table-responsive">
          <center><h3>Sleeve grading</h3></center>
          <table class="table table-hover">
            <thead class="text-warning">
              <th>Name</th>
              <th>Text</th>
              <th>Actions</th>
            </thead>
            <tbody>
              <% @sleeve.each do |s| %>
              <tr>
                <td><%= s.name %></td>
                <td><%= s.text %></td>
                <td><%= link_to 'Delete',  s,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <center><%= link_to "New", new_sleeve_grading_path %></center>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/admin/labels.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-6">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <center><h3>Labels</h3></center>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>Name</th>
                  <th>Shortname</th>
                  <th>Image</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @labels.each do |c| %>
                  <tr>
                    <td><%= c.name %></td>
                    <td><%= c.long_name %></td>
                    <td>
                      <% if c.image_label.present? %>
                        <%= image_tag c.image_label.admin.url, class: "img-fluid", size: '65x65' %>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to 'Edit', edit_record_company_path(c) %> ·
                      <%= link_to 'Delete',  c,  method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
    </div>
    <div class="col-md-6">
      <div class="card card-stats">
        <div class="card-body table-responsive">
          <center><h3>Actions</h3></center>
          <center><%= button_to 'New',{:controller => "record_companies", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %></center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/records.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
  .front {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <br>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>ID</th>
                  <th>Title</th>
                  <th>Artist</th>
                  <th>Front</th>
                  <th>Back</th>
                  <th>Media</th>
                  <th>Sleeve</th>
                  <th>Country</th>
                  <th>Year</th>
                  <th>Special attributes</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @posts.each do |post| %>
                  <tr>
                    <td><%= post.id %></td>
                    <td><%= post.title %></td>
                    <td><%= post.artist.name %></td>
                    <td>
                      <% if post.image_front.present? %>
                        <%= image_tag post.image_front.admin.url, class: "img-fuid front" %>
                      <% else %>
                        <%= image_tag url_for("default.png"), class: "img-fuid front", size: '65x65' %>
                      <% end %>
                    </td>
                    <td>
                      <% if post.image_back.present? %>
                        <%= image_tag post.image_back.admin.url %>
                      <% else %>
                        <%= image_tag url_for("default.png"), class: "img-fuid front", size: '65x65' %>
                      <% end %>
                    </td>
                    <td><%= post.media_grading.name %></td>
                    <td><%= post.sleeve_grading.name %></td>

                    <td>

                    </td>
                    <td><%= post.year %></td>
                    <!-- Special attributes -->
                    <td>
                      <% if post.featured? %>
                        <b>Featured</b><br>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to 'Edit', edit_post_path(post) %> ·
                      <%= link_to 'Delete',  post,  method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
          <div class="card card-stats">
            <div class="card-body table-responsive text-center">
              <h5>Advanced</h5>
              <%= button_to 'New record',{:controller => "posts", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %>
            </div>
          </div>
       </div>
    </div>
  </div>

app/views/admin/stores.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-9">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <center><h3>Stores</h3></center>
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>Name</th>
                  <th>Description</th>
                  <th>Address</th>
                  <th>Actions</th>
                  <th>Map</th>
                </thead>
                <tbody>
                  <% @stores.each do |c| %>
                  <tr>
                    <td><%= c.name %></td>
                    <td><%= c.description %></td>
                    <td><%= c.address %></td>
                    <td><%= link_to 'Edit', edit_store_path(c) %> · <%= link_to 'Delete',  c,  method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <td width="30%">
                      <% if c.address.present? %>
                      <iframe
                        width="300"
                        height="170"
                        frameborder="0"
                        scrolling="no"
                        marginheight="0"
                        marginwidth="0"
                        src="https://maps.google.com/maps?q=<%= c.latitude %>,<%= c.longitude %>&hl=es;z=14&amp;output=embed">
                       </iframe>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
    </div>
    <div class="col-md-3">
      <div class="card card-stats">
        <div class="card-body table-responsive">
          <center><h3>Actions</h3></center>
          <center><%= button_to 'New',{:controller => "stores", :action => "new"} , {:method=>:get, class: 'btn btn-primary'} %></center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users.html.erb
<style type="text/css">
  .text-warning{
    color: #895392!important;
  }
  td {
    display: table-cell!important;
    vertical-align: inherit!important;
  }
  .front {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
          <div class="card card-stats">
            <div class="card-body table-responsive">
              <table class="table table-hover">
                <thead class="text-warning">
                  <th>ID</th>
                  <th>Email</th>
                  <th>Created</th>
                  <th>Updated</th>
                  <th>Actions</th>
                </thead>
                <tbody>
                  <% @users.each do |user| %>
                  <tr>
                    <td><%= user.id %></td>
                    <td><%= user.email %></td>
                    <td><%= user.created_at %></td>
                    <td><%= user.updated_at %></td>
                    <td>

                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
  </div>

app/views/filters/_artist.html.erb
<% if params[:artist] %>
<% else %>
<div class="filter-year">
  <span style="font-weight: bold;">Artist</span>
  <br>
  <% artists = Array.new %>
  <% @posts_all.each do |post| %>
     <% artists << post.artist.name %>
  <% end %>
  <% b = Hash.new(0) %>
  <% artists.each do |v| %>
     <% b[v] += 1 %>
  <% end %>
  <% b.each do |k, v| %>
    <span>
      <%= link_to k, params.merge({:artist => k}).to_enum.to_h  %>
    </span>
    <br>
  <% end %>
 </div>
<% end %>

app/views/filters/_booleans.html.erb
<div class="filter-year">
  <script tye="text/javascript">
    $(':checkbox').click(function() {
    var checked = $(':checkbox').prop('checked');
    if (checked)
        alert('yes');
    else
        alert('no');
    });
  </script>
  <br>
  <div class="checkbox">
  <label>
    <input type="checkbox">
    <span class="box"></span>
    Featured
  </label>
</div>
</div>

app/views/filters/_country.html.erb
<% if params[:country] %>
<% else %>
<div class="filter-year">
  <span style="font-weight: bold;">Country</span>
  <br>
  <% countries = Array.new %>
  <% @posts_all.each do |post| %>
     <% countries << post.country.name %>
  <% end %>
  <% b = Hash.new(0) %>
  <% countries.each do |v| %>
     <% b[v] += 1 %>
  <% end %>
  <% b.each do |k, v| %>
    <span>
      <%= link_to k, params.merge({:country => k}).to_enum.to_h  %>
    </span>
    <br>
  <% end %>
 </div>
<% end %>

app/views/filters/_current.html.erb
<% if params[:artist] %>
<div class="alert alert-primary row filter-close-button">
<p class="filter">Artist: <br><b><%= params[:artist] %></b></p>
<%= link_to secure_path_for(params, :artist) do %>
  <span aria-hidden="true"><i class="material-icons">clear</i></span>
<% end %>
</div>
<% end %>
<% if params[:label] %>
<div class="alert alert-primary row filter-close-button">
<p class="filter">Label: <br><b><%= params[:label] %></b></p>
<%= link_to secure_path_for(params, :label) do %>
  <span aria-hidden="true"><i class="material-icons">clear</i></span>
<% end %>
</div>
<% end %>
<% if params[:country] %>
<div class="alert alert-primary row filter-close-button">
<p class="filter">Country: <br><b><%= params[:country] %></b></p>
<%= link_to secure_path_for(params, :country) do %>
  <span aria-hidden="true"><i class="material-icons">clear</i></span>
<% end %>
</div>
<% end %>
<% if params[:year] %>
<div class="alert alert-primary row filter-close-button">
<p class="filter">Year: <br><b><%= params[:year] %></b></p>
<%= link_to secure_path_for(params, :year) do %>
  <span aria-hidden="true"><i class="material-icons">clear</i></span>
<% end %>
</div>
<% end %>
<% if params[:store] %>
<center>
<span>Store: <b><%= params[:store] %></b></span>
</center>
<% end %>
<% if params[:buyed] %>
<center>
<span>Buyed at <b><%= params[:buyed] %></b></span>
</center>
<% end %>

app/views/filters/_label.html.erb
<% if params[:label] %>
<% else %>
<div class="filter-year">
  <span style="font-weight: bold;">Label</span>
  <br>
  <% labels = Array.new %>
  <% @posts_all.each do |post| %>
     <% labels << post.record_company.name %>
  <% end %>
  <% b = Hash.new(0) %>
  <% labels.each do |v| %>
     <% b[v] += 1 %>
  <% end %>
  <% b.each do |k, v| %>
    <span>
      <%= link_to k, params.merge({:label => k}).to_enum.to_h %>
    </span>
    <br>
  <% end %>
 </div>
<% end %>

app/views/filters/_year.html.erb
<% if params[:year] %>
<% else %>
<div class="filter-year">
  <span style="font-weight: bold;">Year</span>
  <br>
  <% years = Array.new %>
  <% @posts_all.each do |post| %>
     <% if post.year %>
        <% years << post.year %>
     <% end %>
  <% end %>
  <% b = Hash.new(0) %>
  <% years.each do |v| %>
     <% b[v] += 1 %>
  <% end %>
  <% b.first(6).each do |k, v| %>
    <span>
      <%= link_to k, params.merge({:year => k}).to_enum.to_h %>
    </span>
    <br>
  <% end %>
 </div>
<% end %>

app/views/shared/_admin_footer.html.erb
</aside> <!-- col.// -->
</div> <!-- row.// -->
</div>
<!--container end.//-->

app/views/shared/_adminnavbar.html.erb
<div align="center">
  <table border="0" class="admin-navbar">
    <tr>
      <th><%= link_to "Artists", admin_artists_path %></th>
      <th> · </th>
      <th><%= link_to "Records", admin_records_path %></th>
      <th> · </th>
      <th><%= link_to "Grading", admin_grading_path %></th>
      <th> · </th>
      <th><%= link_to "Countries", admin_countries_path %></th>
      <th> · </th>
      <th><%= link_to "Labels", admin_labels_path %></th>
      <th> · </th>
      <th><%= link_to "Formats", admin_formats_path %></th>
      <th> · </th>
      <th><%= link_to "Stores", admin_stores_path %></th>
      <th> · </th>
      <th><%= link_to "Blog", admin_articles_path %></th>
      <th> | </th>
      <th><%= link_to "Users", admin_users_path %></th>
      <th> · </th>
      <th><%= link_to "Settings", admin_settings_path %></th>
    </tr>
  </table>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav class="">
      <ul>
        <li>
          <a href="https://www.instagram.com/phoenix_records_" target="_blank" data-original-title="Follow me on Instagram" style="font-size:18px!important;">
            <i class="material-icons fa fa-instagram"></i>
          </a>
        </li>
        <li>
          <a class="social-icons" href="https://github.com/phoenix-blaze-dev/phoenix-records" target="_blank" data-original-title="Follow me on Instagram" style="font-size:18px!important;">
            <i class="material-icons fa fa-github"></i>
          </a>
        </li>
      </ul>
      <ul>
        <li>
          <a href="/about">
            About Me
          </a>
        </li>
        <li>
          <a href="/blog">
            Blog
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright">
      &copy;
      <%= Time.current.year %>, made with <i class="material-icons">favorite</i> by
      <a href="https://github.com/phoenix-blaze-dev" target="_blank">Phoenix Blaze</a>
    </div>
  </div>
</footer>

app/views/shared/_message.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container" style="position: relative;">
    <%= link_to "Phoenix Records", root_path, class: "navbar-brand core-sprite hide-text" %>
    <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span>
          <i class="fa fa-navicon"></i>
      </span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_tag(posts_path, method: :get, remote: true, id: "search_form", class: "form-inline my-2 my-lg-0 ml-md-auto") do %>
        <%= text_field_tag :title, nil, placeholder: 'Search...', class: 'form-control mr-sm-2 text-center' %>
      <% end %>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Artists", artists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", articles_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>